In [2]:
import numpy as np

In [3]:
def derivate(arr,matrix):
    for i in arr:
        if i <= 0:
            matrix = np.roll(matrix, shift=i-1, axis=0)-matrix
        else:
            matrix = np.roll(matrix, shift=-i, axis=1)-matrix
    return matrix

In [4]:
k=4
A = [[0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 0, 1]
     ]

In [5]:
d1 = [1,0,0]
d2 = [1,1,0]

r1 = derivate(d1,A)
r2 = derivate(d2,A)
relation1 = 2*(r1-r2)
print(relation1)

[[ 0  0  0  0]
 [ 0  0  2 -2]
 [ 0 -2  0  2]
 [ 0  2 -2  0]]


In [6]:
d1 = [1,1,1,1,0,0]
d2 = [1,1,0,0,0,0]

r1 = derivate(d1,A)
r2 = derivate(d2,A)
relation2 = r1-r2
print(relation2)

[[ 0  4 -8  4]
 [-4  0  8 -4]
 [ 8 -8  0  0]
 [-4  4  0  0]]


In [9]:
from itertools import combinations_with_replacement

vals = [3, 2, 1, 0, -1, -2]
DERS = [list(reversed(c))                 # make them nonincreasing
        for c in combinations_with_replacement(sorted(vals), 4)]
print(len(DERS))
mats = []
for der in DERS:
    mats.append(derivate(der,A))





126


In [10]:
from sympy import Matrix, linsolve

A = Matrix(relation1)

Ms = [Matrix(M) for M in mats]

B = Matrix.hstack(*[M.reshape(16, 1) for M in Ms])
b = A.reshape(16, 1)

solset = linsolve((B, b))
sol = next(iter(solset), None)

if sol is not None and all(s.is_integer is True for s in sol):
    print("YES:", [int(s) for s in sol])
else:
    print("NO")


NO
